version: '3.8'

networks:
  default:
    name: 'dts'

volumes:
  dts-pg:
  dts-logs:
  dts-prom:
  dts-grafana:

services: 
  postgres:
    container_name: 'dts-pg'
    image: 'postgres:17.0-alpine'
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: 'mysecretpassword'
    volumes:
      - dts-pg:/var/lib/postgresql/data

  aspire-dashboard:
    container_name: 'dts-aspire-dashboard'
    image: mcr.microsoft.com/dotnet/aspire-dashboard:9.0
    ports:
      - "18888:18888"
      - "4317:18889"
    environment:
      DOTNET_DASHBOARD_UNSECURED_ALLOW_ANONYMOUS: 'true'