scrape_configs:
  - job_name: dts-scrape
    scrape_interval: 10s
    scrape_timeout: 3s
    static_configs:
      - targets:
          - localhost:9090
          - localhost:5005
        labels:
          app: dts